// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxwG3vOYV93xUDRoO0a3UmeXV54VPTpYY',
    appId: '1:534781193499:web:44c5f2445d70e8e27a77be',
    messagingSenderId: '534781193499',
    projectId: 'echotune-cb662',
    authDomain: 'echotune-cb662.firebaseapp.com',
    storageBucket: 'echotune-cb662.firebasestorage.app',
    measurementId: 'G-SYDG9MT424',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArROqFISYUbb4en6Ev1HEquXKju1Jx7YQ',
    appId: '1:534781193499:ios:5090c9291dcdd4b67a77be',
    messagingSenderId: '534781193499',
    projectId: 'echotune-cb662',
    storageBucket: 'echotune-cb662.firebasestorage.app',
    iosBundleId: 'com.example.echotune',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyArROqFISYUbb4en6Ev1HEquXKju1Jx7YQ',
    appId: '1:534781193499:ios:5090c9291dcdd4b67a77be',
    messagingSenderId: '534781193499',
    projectId: 'echotune-cb662',
    storageBucket: 'echotune-cb662.firebasestorage.app',
    iosBundleId: 'com.example.echotune',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAxwG3vOYV93xUDRoO0a3UmeXV54VPTpYY',
    appId: '1:534781193499:web:85088a372f51de627a77be',
    messagingSenderId: '534781193499',
    projectId: 'echotune-cb662',
    authDomain: 'echotune-cb662.firebaseapp.com',
    storageBucket: 'echotune-cb662.firebasestorage.app',
    measurementId: 'G-9SXQ08HS5R',
  );
}
